import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import { chromium } from 'playwright';
const browser=await chromium.launch({channel:process.env.RALLY_BROWSER_CHANNEL,headless:true});
const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const choose=async(label,value)=>{await page.getByRole('combobox',{name:label,exact:true}).click();await page.getByRole('option',{name:value,exact:true}).click()};
const saved=()=>page.getByText('端末に保存済み',{exact:true}).waitFor();
const add=async team=>{await page.locator('.score-card.team-'+team).click();await saved()};
const settings=async action=>{await page.getByRole('button',{name:'設定',exact:true}).click();await page.getByRole('button',{name:action,exact:true}).click()};
const noDialog=()=>page.getByRole('dialog').waitFor({state:'hidden'});
try{
 await page.goto('http://127.0.0.1:4180/');await page.getByRole('button',{name:'試合を設定',exact:true}).click();
 await choose('得点ルール','21点制');
 await page.getByLabel('A1 選手名',{exact:true}).fill('John');await page.getByLabel('B1 選手名',{exact:true}).fill('Bob');await page.getByRole('button',{name:'この設定で試合を開始',exact:true}).click();await saved();
 await add('a');await add('a');await add('b');
 await settings('試合設定を変更');assert.equal(await page.getByRole('combobox',{name:'得点ルール',exact:true}).textContent(),'21点制▼');
 await choose('得点ルール','15点制');await choose('最初のサーバー','A2');await choose('最初のレシーバー','B2');
 await mkdir('outputs',{recursive:true});await page.screenshot({path:'outputs/edit-match-settings.png',fullPage:true});
 await page.getByRole('button',{name:'変更を保存',exact:true}).click();await saved();await noDialog();
 assert.equal(await page.locator('.score-card.team-a .score-number').textContent(),'2');assert.equal(await page.locator('.score-card.team-b .score-number').textContent(),'1');
 assert.equal(await page.locator('.server strong').textContent(),'Bob');
 await page.reload();await saved();await settings('試合設定を変更');assert.equal(await page.getByRole('combobox',{name:'得点ルール',exact:true}).textContent(),'15点制▼');assert.equal(await page.getByRole('combobox',{name:'最初のサーバー',exact:true}).textContent(),'A2▼');
 await choose('種目','シングルス');await page.getByRole('button',{name:'変更を保存',exact:true}).click();await saved();await noDialog();assert.equal(await page.locator('.court-player').count(),2);
 await settings('ゲームセット');await choose('終了理由','棄権');assert.ok(await page.getByRole('button',{name:'ゲームセットを確定',exact:true}).isDisabled());await choose('終了する範囲','試合全体を終了');await choose('結果','Team B の勝利');
 await page.screenshot({path:'outputs/game-set-confirm.png',fullPage:true});await page.getByRole('button',{name:'ゲームセットを確定',exact:true}).click();await saved();await noDialog();
 assert.ok(await page.locator('.score-card.team-a').isDisabled());assert.equal(await page.locator('.serve-arrow').count(),0);assert.match(await page.locator('.sheet-section').innerText(),/棄権/);
 await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();await saved();assert.ok(await page.locator('.score-card.team-a').isDisabled());assert.equal(await page.locator('.score-card.team-a .score-number').textContent(),'2');
 await page.getByRole('button',{name:'戻る',exact:true}).click();await saved();assert.ok(await page.locator('.score-card.team-a').isEnabled());assert.equal(await page.locator('.score-card.team-b .score-number').textContent(),'1');await page.getByRole('button',{name:'進む',exact:true}).click();await saved();assert.ok(await page.locator('.score-card.team-a').isDisabled());await page.getByRole('button',{name:'戻る',exact:true}).click();await saved();await context.setOffline(false);
 await settings('ゲームセット');await choose('結果','引き分け');await page.getByRole('button',{name:'ゲームセットを確定',exact:true}).click();await saved();
 await page.getByRole('button',{name:'次のセットへ',exact:true}).click();await choose('最初にサーブするチーム','Team B');await page.getByRole('button',{name:'GAME 2 を開始',exact:true}).click();await saved();assert.equal(await page.locator('.server strong').textContent(),'Bob');
 await page.getByRole('button',{name:'戻る',exact:true}).click();await saved();assert.equal(await page.locator('.score-card.team-a .score-number').textContent(),'2');assert.ok(await page.locator('.score-card.team-a').isEnabled());
 await page.getByRole('button',{name:'設定',exact:true}).click();await choose('言語','English');await page.getByRole('button',{name:'End game',exact:true}).click();
 assert.ok(!/[\u3040-\u30ff\u3400-\u9fff]/.test(await page.getByRole('dialog').innerText()));await choose('What to end','Entire match');await choose('Result','Draw');await page.getByRole('button',{name:'Confirm ending',exact:true}).click();await page.getByText('Saved on device',{exact:true}).waitFor();await noDialog();await page.screenshot({path:'outputs/game-set-english.png',fullPage:true});assert.match(await page.locator('.result-strip').innerText(),/Match over/);
 await page.getByRole('button',{name:'Match history',exact:true}).click();await page.locator('.history-item').first().waitFor();assert.match(await page.locator('.history-item').innerText(),/Time limit/);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export current match',exact:true}).click();const download=await downloadPromise;await download.saveAs('outputs/corrected-match.json');await page.locator('input[type=file]').setInputFiles('outputs/corrected-match.json');await page.getByText('Saved 1 matches as copies.',{exact:true}).waitFor();assert.equal(await page.locator('.history-item').count(),2);
 assert.deepEqual(errors,[]);const result={checks:['edit preset and initial service without losing scores','settings persist and allow singles conversion','explicit retirement winner and match ending','no scoring after manual end','offline restore and Undo/Redo without losing a point','drawn game and next-server selection','English manual ending and history','JSON round trip'],errors};console.log(JSON.stringify(result,null,2));await writeFile('outputs/corrections-results.json',JSON.stringify(result,null,2));
}finally{await browser.close()}
